/**
 * Real screenshots of the actual apps -> Work card thumbnails.
 *
 * The CI/sandbox has no GPU browser, so the WebGL/Canvas apps must be
 * captured on a real machine. Run this locally:
 *
 *   npm i -D playwright && npx playwright install chromium
 *   npm run build && npm start            # in one terminal
 *   node scripts/shots.mjs                # in another
 *
 * It writes public/shots/<slug>.png and regenerates
 * src/data/shots.generated.ts. Commit both. The Work cards pick the
 * images up automatically (no broken images before they exist).
 *
 * Override the local origin with BASE_URL=http://localhost:4000 etc.
 */
import { chromium } from "playwright";
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const BASE = process.env.BASE_URL ?? "http://localhost:3000";

// slug -> URL. Internal routes resolve against BASE; externals are absolute.
const TARGETS = {
  dashboard: `${BASE}/work/dashboard`,
  "space-invaders": `${BASE}/work/space-invaders`,
  "mandelbulb-playground": `${BASE}/work/mandelbulb-playground`,
  "component-lab": `${BASE}/work/component-lab`,
  "particle-gravity": `${BASE}/work/particle-gravity`,
  "wave-synth": `${BASE}/work/wave-synth`,
  breakout: `${BASE}/work/breakout`,
  "git-pulse": `${BASE}/work/git-pulse`,
  "color-extractor": `${BASE}/work/color-extractor`,
  "fractal-poster-press": `${BASE}/work/fractal-poster-press`,
  "preview-links": "https://previewlinks.xyz",
  "rich-media-builder": "https://rich-media-builder-one.vercel.app",
  pottyfolly: "https://pottyfolly-chabays-projects.vercel.app",
};

const OUT_DIR = join(ROOT, "public", "shots");
const GEN = join(ROOT, "src", "data", "shots.generated.ts");

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const run = async () => {
  await mkdir(OUT_DIR, { recursive: true });
  const browser = await chromium.launch();
  const page = await browser.newPage({
    viewport: { width: 1440, height: 900 },
    deviceScaleFactor: 2,
  });

  const captured = {};
  for (const [slug, url] of Object.entries(TARGETS)) {
    try {
      process.stdout.write(`• ${slug} … `);
      await page.goto(url, { waitUntil: "networkidle", timeout: 45000 });
      // let canvas / WebGL / animations warm up and reach a nice frame
      await sleep(4500);
      const file = join(OUT_DIR, `${slug}.png`);
      await page.screenshot({
        path: file,
        clip: { x: 0, y: 0, width: 1440, height: 900 },
      });
      captured[slug] = `/shots/${slug}.png`;
      console.log("ok");
    } catch (err) {
      console.log(`skipped (${err.message.split("\n")[0]})`);
    }
  }

  await browser.close();

  const body =
    "// AUTO-GENERATED by scripts/shots.mjs — do not edit by hand.\n" +
    "export const SHOTS: Record<string, string> = " +
    JSON.stringify(captured, null, 2) +
    ";\n";
  await writeFile(GEN, body);
  console.log(
    `\n${Object.keys(captured).length}/${
      Object.keys(TARGETS).length
    } captured → public/shots + src/data/shots.generated.ts`,
  );
};

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
