// AUTO-GENERATED by scripts/shots.mjs — do not edit by hand.
// Maps project slug -> /public path of its real captured screenshot.
// Empty until you run `node scripts/shots.mjs` locally (the sandbox has
// no GPU browser, so WebGL/Canvas apps must be shot on a real machine).
export const SHOTS: Record<string, string> = {};
